name: Billboards
main: de.blablubbabc.billboards.Billboards
version: 1.2
author: blablubbabc
description: Rent-able signs.
depend: [Vault]
commands:
    billboard:
      description: Used to add a sign.
      usage: /<command> [<price> <duration>]
      aliases: adsign
permissions:
  billboards.admin:
    description: Can add, remove all billboard signs.
    default: op
  billboards.rent:
    description: Can rent and edit own billboard signs.
    default: true