name: Billboards
main: de.blablubbabc.billboards.Billboards
version: 1.7
author: blablubbabc
description: Rent-able signs.
depend: [Vault]
commands:
    billboard:
      description: Used to add a sign.
      usage: /<command> [<price> <duration>] [creator]
      aliases: adsign
permissions:
  billboards.rent:
    description: Can rent and edit own billboard signs.
    default: true
  billboards.create:
    description: Can create own billboard signs.
    default: false
  billboards.admin:
    description: Can add and remove all billboard signs.
    default: op
    children:
      billboards.rent: true
      billboards.create: true