name: Billboards
main: de.blablubbabc.billboards.BillboardsPlugin
api-version: '1.13'
version: '${version}'
authors:
  - blablubbabc
  - MrXiaoM
description: Rent-able signs.
depend:
  - Vault
  - ProtocolLib
softdepend:
  - PlaceholderAPI
folia-supported: true
load: STARTUP
commands:
  billboard:
    description: Used to add a sign.
    usage: /<command> [<price> <duration>] [creator]
    aliases: [billboards, adsign]
permissions:
  billboards.rent:
    description: Can rent and edit own billboard signs.
    default: true
  billboards.create:
    description: Can create own billboard signs.
    default: false
  billboards.sign.color:
    description: Can use color code on signs.
    default: op
  billboards.sign.format:
    description: Can use format code on signs.
    default: op
  billboards.sign.format.magic:
    description: Can use magic code (§k) on signs.
    default: op
  billboards.admin:
    description: Can add and remove all billboard signs.
    default: op
    children:
      billboards.rent: true
      billboards.create: true